// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package models

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO accounts (owner, balance, currency) VALUES ($1, $2, $3) RETURNING id, owner, balance, currency, created_at
`

type CreateParams struct {
	Owner    string `json:"owner"`
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Account, error) {
	row := q.db.QueryRow(ctx, create, arg.Owner, arg.Balance, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, owner, balance, currency, created_at FROM accounts WHERE id = $1 FOR NO KEY UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, owner, balance, currency, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getList = `-- name: GetList :many
SELECT id, owner, balance, currency, created_at FROM accounts
`

func (q *Queries) GetList(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, getList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE accounts SET balance = $1 WHERE id = $2 RETURNING id, owner, balance, currency, created_at
`

type UpdateBalanceParams struct {
	Balance   int64 `json:"balance"`
	Accountid int64 `json:"accountid"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateBalance, arg.Balance, arg.Accountid)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const updateOwner = `-- name: UpdateOwner :exec
UPDATE accounts SET owner = $2 WHERE id = $1
`

type UpdateOwnerParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) UpdateOwner(ctx context.Context, arg UpdateOwnerParams) error {
	_, err := q.db.Exec(ctx, updateOwner, arg.ID, arg.Owner)
	return err
}
